name: lumberjack
description: A Lumberjack for future projects.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  go_router: ^10.2.0
  shared_preferences: ^2.2.2
  collection: ^1.17.2
  get_it: ^7.6.4
  flutter_svg: ^2.0.9
  provider: ^6.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true